class CustomException(Exception):
    pass


class AnotherCustomException(Exception):
    pass
